# Generated by Django 5.0.3 on 2024-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_custumeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custumeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custumeuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='custumeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
