# Generated by Django 5.0.3 on 2024-04-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_custumeuser_is_active_custumeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.EmailField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.custumeuser')),
            ],
        ),
    ]
