# Generated by Django 5.0.3 on 2024-04-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_course_chatgroup_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='Default Group Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='participants',
            field=models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
