# Generated by Django 5.0.3 on 2024-04-05 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_message_group_remove_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_feelings', models.IntegerField(choices=[(1, 'לא עזר בכלל'), (2, 'עזר מעט'), (3, 'עזר במידה מסוימת'), (4, 'עזר מאוד')])),
                ('academic_progress', models.IntegerField(choices=[(1, 'לא עזר בכלל'), (2, 'עזר מעט'), (3, 'עזר במידה מסוימת'), (4, 'עזר מאוד')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
