# Generated by Django 5.0.3 on 2024-04-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_questionnaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumeuser',
            name='profile_pic',
            field=models.ImageField(default='default_images/default_profile_pic.jpg', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='custumeuser',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
